version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./checkmate.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6" # Applies to 32-bit ARM
    goamd64:
      - v1 # Needed for reproducible builds

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/adedayo/checkmate:latest"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/adedayo/checkmate:v{{ .Tag }}"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    extra_files:
      - dist/checkmate_linux_amd64_v1/checkmate

brews:
  - repository:
      owner: adedayo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    commit_author:
      name: "Dayo Adetoye"
      email: dayo.dev@gmail.com
    caveats: "To get help running CheckMate please run: checkmate --help "
    homepage: "https://github.com/adedayo/checkmate"
    description: "CheckMate is a code security analysis tool."
    license: "BSD-3-Clause"

release:
  github:
    owner: adedayo
    name: checkmate
