version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./checkmate.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6" # Applies to 32-bit ARM
    goamd64:
      - v1 # Needed for reproducible builds

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/adedayo/checkmate:latest-amd64"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}-amd64"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/adedayo/checkmate:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - image_templates:
      - "ghcr.io/adedayo/checkmate:latest-arm64"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}-arm64"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/adedayo/checkmate:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

docker_manifests:
  - name_template: "ghcr.io/adedayo/checkmate:{{ .Tag }}"
    image_templates:
      - "ghcr.io/adedayo/checkmate:{{ .Tag }}-amd64"
      - "ghcr.io/adedayo/checkmate:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/adedayo/checkmate:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "ghcr.io/adedayo/checkmate:v{{ .Major }}"
    image_templates:
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}-amd64"
      - "ghcr.io/adedayo/checkmate:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/adedayo/checkmate:latest"
    image_templates:
      - "ghcr.io/adedayo/checkmate:latest-amd64"
      - "ghcr.io/adedayo/checkmate:latest-arm64"


brews:
  - repository:
      owner: adedayo
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    commit_author:
      name: "Dayo Adetoye"
      email: dayo.dev@gmail.com
    directory: "."
    caveats: "To get help running CheckMate please run: checkmate --help "
    homepage: "https://github.com/adedayo/checkmate"
    description: "CheckMate is a code security analysis tool."
    license: "BSD-3-Clause"
    install: |
      bin.install "checkmate"
    test: |
      system "#{bin}/checkmate", "--version"

release:
  github:
    owner: adedayo
    name: checkmate
  mode: replace
  replace_existing_artifacts: true
