version: 2
project_name: checkmate
builds:
  - main: ./checkmate.go
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - "v1"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
before:
  hooks:
    - go mod download
brews:
  - repository:
      owner: adedayo
      name: homebrew-tap
    commit_author:
      name: "Dayo Adetoye"
      email: dayo.dev@gmail.com
    caveats: "To get help running CheckMate please run: checkmate --help "
    homepage: "https://github.com/adedayo/checkmate"
    description: "CheckMate is a code security analysis tool."
    license: "BSD-3-Clause"
