name: "Checkmate Secret Scanner"
description: "Scan repositories for secrets using Checkmate"
author: "Dr. Dayo Adetoye <https://dayo-adetoye.com>"
branding:
  icon: "shield"
  color: "blue"
outputs:
  findings:
    description: "Scan results"
    value: ${{ steps.scan.outputs.findings }}
runs:
  using: "composite"
  steps:
    - name: Run Checkmate Secret Scanner
      id: scan
      run: |
        docker run --rm -v ${{ github.workspace }}:/data ghcr.io/adedayo/checkmate search /data --json > results.json
        cat results.json
        echo "findings=$(cat results.json | jq -c .)" >> $GITHUB_ENV
      shell: bash
