package common

var (
	//AppName is the application name
	AppName        = "checkmate"
	sourceFileExts = "java,scala,groovy,jsp,do,jad,c,cc,cxx,cpp,cp,c++,bcc,php2,php,c--,hc,hpp,hxx,m,swift,h,cs,c#,vb,vba,vbs,aspx,py,pyt,rb,erb,lua,asmx,f,f95,ash,tcl,ml,pl,cbl"
	//SourceFileExtensions extensions for source code
	SourceFileExtensions = makeMap(sourceFileExts)
	//TextFileExtensions file name extensions for textual files
	TextFileExtensions = makeMap("txt,xml,docx,xlsx,pptx,odt,fodt,ods,fods,odp,fodp,odb,js,json,yml,yaml,md,cnf,conf,config,sh,zsh,bash,cmd,sql,bat,pp,key,csr,crt,pem,csv,cf,pre,htm,html," + sourceFileExts)

	//DangerousFileNames are file names commonly associated with secrets, should not be stored in source code management systems
	DangerousFileNames = map[string]string{
		`id_rsa`:   `SSH private key`,
		`id_dsa`:   `SSH private key`,
		`keystore`: `Java key store`,
	}
	//CertsAndKeyStores are potential certificate and keystore files that should not be stored in source code repositories
	CertsAndKeyStores = map[string]string{
		`.pem`:      `Certificate file`,
		`.crt`:      `Certificate file`,
		`.cer`:      `Certificate file`,
		`.der`:      `Certificate file`,
		`.p7b`:      `Certificate file`,
		`.p7r`:      `Certificate file`,
		`.spc`:      `Certificate file`,
		`.pfx`:      `Certificate file`,
		`.p12`:      `Certificate file`,
		`.jks`:      `Java key store`,
		`.ks`:       `Java key store`,
		`.keystore`: `Java key store`,
		`.jceks`:    `Java key store`,
		`.ubr`:      `Java key store`,
		`.bks`:      `Java key store`,
		`.sst`:      `Microsoft certificate store`,
		`.sto`:      `Microsoft certificate stor`,
	}
	//FinancialAndAccountingExtensions are file extensions that may contain financial accounting data: not to be stored in source code repositories or other shared spaces
	//see https://www.file-extensions.org/filetype/extension/name/financial-tax-files/sortBy/extension/order/asc/page/1
	FinancialAndAccountingExtensions = map[string]string{
		`.#vc`:         `Big Fish ViewChoice data`,
		`.$ac`:         `$&Sense data`,
		`.00c`:         `ProFile 2000 autosave data`,
		`.07g`:         `ProSeries Tax data`,
		`.07i`:         `ProSeries tax data`,
		`.08i`:         `QuickBooks return tax`,
		`.09i`:         `ProSeries Tax data`,
		`.09t`:         `StudioTax 2009 income tax`,
		`.10t`:         `StudioTax income tax`,
		`.11t`:         `StudioTax income tax data`,
		`.13t`:         `Intuit Profile Premier data`,
		`.1pa`:         `QuickBooks form`,
		`.1pe`:         `TurboTax tax form`,
		`.2009`:        `Any data file created in 2009`,
		`.2012`:        `Any data file created in 2012`,
		`.2013`:        `Any data file created in 2013`,
		`.2015`:        `Any data file created in 2015`,
		`.2016`:        `Any data file created in 2016`,
		`.210`:         `StarMoney bpd hbcioffl 280 data`,
		`.3me`:         `TurboTax form`,
		`.3pe`:         `TurboTax 2008 form`,
		`.500`:         `Tally.ERP accounting data`,
		`.ab4`:         `AB4 Accounting & Business data`,
		`.ac2`:         `Banana 4 accounting data`,
		`.acc`:         `Graphic Accounts account data`,
		`.ach`:         `Medlin Payroll Software automated clearing house data or eSignal file`,
		`.aci`:         `ACI development appraisal`,
		`.acm`:         `eSignal file`,
		`.acr`:         `Medlin Payroll Software accrual method adjustments / unpaid invoices file`,
		`.afm`:         `Abassis data`,
		`.aif`:         `QuickBooks Accountant's Review copy data`,
		`.amj`:         `AceMoney database`,
		`.ati`:         `Microsoft Office Accounting updated company data`,
		`.bai`:         `Bank Administration Institute format`,
		`.bc8`:         `Cashflow Manager backup`,
		`.bc9`:         `Cashflow Manager backup`,
		`.bd2`:         `Lacerte Tax tax file`,
		`.bd3`:         `Lacerte Tax data`,
		`.bgt`:         `Quicken 2002 internet common data or Graphic Accounts budget data`,
		`.bk2`:         `Cashbook Complete data`,
		`.bpf`:         `Business Plan Pro cash compass table formatting data`,
		`.bpw`:         `QuickBooks business planner data`,
		`.brw`:         `PointCentral financial institutions loan or Calyx Point data`,
		`.btif`:        `Bank image TIFF data`,
		`.bxx`:         `Bank of America loan docs`,
		`.cat`:         `Quicken IntelliCharge categorization data`,
		`.cb`:          `Cashbook Complete company data`,
		`.cdf`:         `Nominal Small Business Accounting Software company data`,
		`.cf8`:         `Cashflow Manager data`,
		`.cf9`:         `Cashflow Manager accounting data`,
		`.cfdi`:        `Comprobante Fiscal Digital por Internetdata`,
		`.cfp`:         `QuickBooks cash flow projector`,
		`.ch`:          `eSignal file`,
		`.chg`:         `Quicken online data`,
		`.cht`:         `eSignal data`,
		`.coa`:         `Medlin Payroll Software chart`,
		`.cpw`:         `Online Cost Planning Service cost planning work data`,
		`.cus`:         `Medlin Payroll Software customer data file or Payroll Mate customer data`,
		`.d07`:         `DeductionPro 2007 data`,
		`.dac`:         `Dynacom Accounting data`,
		`.dbat`:        `Quicken for Mac data`,
		`.ddd`:         `Medlin Payroll Software direct deposit information file or Payroll Mate 2008 direct deposit file file`,
		`.defxml`:      `Danea Easyfatt data`,
		`.des`:         `QuickBooks form design template or Medlin Payroll Software sales code information file`,
		`.dgc`:         `TurboTax tax form`,
		`.dsb`:         `eSignal file`,
		`.dtaus`:       `DatenTrägerAustausch data`,
		`.dtl`:         `eSignal file`,
		`.dxi`:         `PayWindow database`,
		`.ebc`:         `CITE Control file`,
		`.ebd`:         `Empower business dashboard file`,
		`.ebq`:         `CITE Electronic Bill of Quantities file`,
		`.ec8`:         `Simplazz 1-2-3 accountant export`,
		`.efs`:         `eSignal formula script`,
		`.efslib`:      `eSignal EFS function library file`,
		`.efw2`:        `AccuWage W-2 form`,
		`.efw2c`:       `AccuWage W-2C form`,
		`.emd`:         `eSignal market depth file`,
		`.emp`:         `Medlin Payroll Software employee data file or eSignal market profile`,
		`.ens`:         `eSignal NewsManager preview file`,
		`.ent`:         `eSignal NewsManager file`,
		`.epa`:         `Electronic Payment Advice format`,
		`.epb`:         `EP Budgeting data`,
		`.eqb`:         `eSignal quote board data`,
		`.esk`:         `eSignal scan`,
		`.ess`:         `eSignal symbol search`,
		`.esv`:         `Principia stock research document`,
		`.etq`:         `eSignal time and quotes file`,
		`.ets`:         `eSignal time and sales data`,
		`.exp`:         `QuickBooks export`,
		`.fa1`:         `DATAIR FAS 87/132 reporter data`,
		`.fa2`:         `DATAIR FAS 87/132 reporter custom text`,
		`.fca`:         `Cost report data`,
		`.fcpa`:        `Officer cost report data file`,
		`.fcpr`:        `Officer cost report data file`,
		`.fcr`:         `Cost report data`,
		`.fef`:         `Steuer2001 data`,
		`.ffd`:         `Fortora Fresh Finance data`,
		`.flk`:         `AccountEdge lock data`,
		`.fnm`:         `Fannie Mae 1003 data`,
		`.fxw`:         `eSignal data`,
		`.fyc`:         `eSignal data`,
		`.gdb`:         `Database`,
		`.gfi`:         `General Index of Financial Information`,
		`.gnc`:         `GnuCash data`,
		`.gpc`:         `ABO financial exchange message`,
		`.gsb`:         `Grisbi data`,
		`.gto`:         `Quicken Online data`,
		`.h10`:         `At Home Canada 2010 tax return`,
		`.h11`:         `At Home 2011 tax return`,
		`.h12`:         `At Home 2012 tax return data`,
		`.hbk`:         `Humanic Software accounting data file`,
		`.hif`:         `Quicken Online data`,
		`.hsr`:         `RezeptAssist import or export file`,
		`.hts`:         `MetaTrader historical data`,
		`.i2b`:         `Invoice2go product`,
		`.ibank`:       `iBank accounting data file`,
		`.iif`:         `QuickBooks interchange format`,
		`.imp`:         `Simple Accounting data`,
		`.int?`:        `Quicken for Mac data`,
		`.intu`:        `Quicken for Mac data`,
		`.inv`:         `Medlin Payroll Software current year checks and invoices`,
		`.itf`:         `eSignal integrated trading data`,
		`.jsd`:         `Jazer financial file`,
		`.jsda`:        `Jazer financial data`,
		`.kb7`:         `Kaikei accounting data`,
		`.kd3`:         `Yayoi Kaikei accounting data`,
		`.kmo`:         `Commercial Bank Czech financial data exchange format`,
		`.kmy`:         `KMyMoney data`,
		`.ldc`:         `Steuer2001 data`,
		`.ldr`:         `eSignal hot list`,
		`.let`:         `Genesis 2000 data`,
		`.lgb`:         `QuickBooks little green box`,
		`.lhr`:         `Quicken Financial Life for Mac financial data`,
		`.lid`:         `Quicken 2002 Deluxe data`,
		`.lin`:         `Medlin Payroll Software current period invoice detail`,
		`.lld`:         `Loan Level Disclosure data`,
		`.lmr`:         `QuickBooks Loan Manager data`,
		`.m10`:         `Microsoft Money 2002 data`,
		`.m11`:         `Microsoft Money 2003 data`,
		`.m12`:         `Microsoft Money 2004 backup data`,
		`.m14`:         `Microsoft Money 2005 backup data`,
		`.m15`:         `Microsoft Money 2006 data`,
		`.m16`:         `Microsoft Money 2007 data file`,
		`.md`:          `Moneydance financial data`,
		`.mem`:         `Medlin Payroll Software additional vendor data file`,
		`.metastock`:   `Metastock data file`,
		`.ml2`:         `MultiLedger budget data`,
		`.ml9`:         `MultiLedger transactions`,
		`.mlb`:         `MultiLedger ship via file`,
		`.mlc`:         `MultiLedger ship to data`,
		`.mmb`:         `Money Manager EX data`,
		`.mmm`:         `Money Manager data`,
		`.mmw`:         `AceMoney financial data`,
		`.mn1`:         `Microsoft Money version 1 data`,
		`.mn2`:         `Microsoft Money version 2 data`,
		`.mn3`:         `Microsoft Money version 3 data`,
		`.mn4`:         `Microsoft Money 95 data file`,
		`.mn5`:         `Microsoft Money 97 data`,
		`.mn6`:         `Microsoft Money 98 data file`,
		`.mn7`:         `Microsoft Money 99 data`,
		`.mn8`:         `Microsoft Money 2000 data file`,
		`.mn9`:         `Microsoft Money 2001 data`,
		`.mne`:         `Microsoft Money data`,
		`.mnp`:         `Ultrasoft Money file`,
		`.mny`:         `Microsoft Money data`,
		`.moneywell`:   `MoneyWell financial data file`,
		`.mql`:         `MetaTrader indicator file`,
		`.mrq`:         `NETFILE tax data`,
		`.mwi`:         `Medlin Payroll Software invoice layout information`,
		`.mws`:         `Medlin Payroll Software statement layout information file`,
		`.mye`:         `MYOB data file`,
		`.myob`:        `MYOB data`,
		`.myox`:        `MYOB data backup`,
		`.n43`:         `Norma43 data`,
		`.nl2`:         `eSignal market depth data`,
		`.nni`:         `ANNI information data`,
		`.npc`:         `QuickBooks online banking data`,
		`.nv`:          `NewViews 1 accounting data file`,
		`.nv2`:         `NewViews 2 accounting data`,
		`.oet`:         `eSignal order entry ticket`,
		`.ofc`:         `Open Financial Connectivity format`,
		`.ofx`:         `Open Financial Exchange format`,
		`.omf`:         `OMF Operation, Management & Finance database file`,
		`.op`:          `eSignal OptionsPlus data`,
		`.p07`:         `2007 CANTAX T1 tax return`,
		`.p08`:         `SApartnership2008 file`,
		`.pcif`:        `PayCycle data`,
		`.pd6`:         `Lacerte Tax data`,
		`.pfd`:         `Personal Finances database`,
		`.pg`:          `eSignal page file`,
		`.pls`:         `MYOB data`,
		`.pma`:         `Payroll Mate file`,
		`.por`:         `eSignal portfolio file`,
		`.pr0`:         `CheckMark Payroll Software company information file`,
		`.pr1`:         `CheckMark Payroll Software employees file`,
		`.pr2`:         `CheckMark Payroll Software employee checks file`,
		`.pr3`:         `CheckMark Payroll Software employer payees file`,
		`.pr4`:         `CheckMark Payroll Software employer checks file`,
		`.pr5`:         `CheckMark Payroll distribution data`,
		`.ptb`:         `Peachtree Complete Accounting backup`,
		`.ptdb`:        `Peachtree Accounting accounting data`,
		`.ptk`:         `Quicken Online data`,
		`.pvc`:         `Sage MAS 90 data file`,
		`.pxa`:         `XpressAccounts data`,
		`.q00`:         `Quicken 2000 tax return`,
		`.q01`:         `Quicken 2001 tax return`,
		`.q06`:         `QuickTax 2006 accounting data`,
		`.q07`:         `QuickTax 2007 tax return data`,
		`.q08`:         `QuickTax 2008 tax return`,
		`.q09`:         `QuickTax 2009 tax return`,
		`.q43`:         `Aqbanking Q43 file format`,
		`.q98`:         `Quicken 98 tax return`,
		`.qb1`:         `Quicken data`,
		`.qb2005`:      `QuickBooks 2005 for Mac backup`,
		`.qb2006`:      `QuickBooks 2006 for Mac backup`,
		`.qb2007`:      `QuickBooks 2007 for Mac backup`,
		`.qb2008`:      `Quickbook 2008 for Mac backup`,
		`.qb2009`:      `QuickBooks 2009 for Mac backup`,
		`.qb2010`:      `QuickBooks 2010 for Mac backup`,
		`.qb2011`:      `QuickBooks 2011 for Mac backup`,
		`.qb2012`:      `QuickBooks 2012 for Mac backup`,
		`.qb2013`:      `QuickBooks 2013 for Mac backup`,
		`.qba`:         `QuickBooks accountant review copy data`,
		`.qbm`:         `QuickBooks portable company data`,
		`.qbmb`:        `QuickBooks backup file`,
		`.qbmd`:        `QuickBooks backup`,
		`.qbo`:         `QuickBooks online bank statement data`,
		`.qbr`:         `QuicBooks report template`,
		`.qbw`:         `QuickBooks company data`,
		`.qbx`:         `QuickBooks Accountant transfer data`,
		`.qby`:         `Quickbooks Accountant's import data`,
		`.qbz`:         `Quick Trial Balance data`,
		`.qch`:         `Quicken for MS-DOS data`,
		`.qdf`:         `Quicken financial data`,
		`.qdfm`:        `Quicken for Mac financial data`,
		`.qdfx`:        `Quicken Essentials for Mac financial data exchange format`,
		`.qdlx`:        `Quicken for Mac data file`,
		`.qdt`:         `QuickBooks UK accountancy data or Quicken data`,
		`.qel`:         `Quicken Electronic library file`,
		`.qem`:         `ExpensAble report`,
		`.qfi`:         `Quicken 2002 financial data`,
		`.qfx`:         `Quicken Financial Exchange format`,
		`.qif`:         `Quicken Interchange Format`,
		`.qix`:         `Quicken DOS data file`,
		`.qme`:         `Quicken Win version 3 file`,
		`.qml`:         `Quicken DOS data file`,
		`.qmt`:         `Quicken memory list file`,
		`.qmtf`:        `Intuit Quicken data`,
		`.qnx`:         `Quicken index file`,
		`.qob`:         `QuickBooks 2010 Pro data`,
		`.qpb`:         `Quicken payroll data`,
		`.qpg`:         `QuickBooks data`,
		`.qph`:         `Intuit Quicken price history file`,
		`.qpi`:         `Quicken for Windows version 3 financial data`,
		`.qsd`:         `Quicken data`,
		`.qsm`:         `QuickBooks Statement Wirter data`,
		`.qtx`:         `Quicken data`,
		`.quicken2015`: `Quicken for Mac 2015 financial data`,
		`.quicken2016`: `Quicken for Mac 2016 financial data`,
		`.quicken2017`: `Quicken for Mac 2017 financial data`,
		`.quickendata`: `Quicken Essentials for Mac financial data file`,
		`.quo`:         `eSignal quote data`,
		`.qw5`:         `Quicken Win version 5 financial data`,
		`.qwmod`:       `Quicken for Windows data`,
		`.qxf`:         `Quicken for Mac data exchange format`,
		`.rcs`:         `SaralTDS eTDS software annual report`,
		`.rda`:         `Ready Ace accounting data`,
		`.rdy`:         `Ready Pro accounting data`,
		`.reb`:         `Reimbursement Tracker data`,
		`.rec`:         `Medlin Payroll Software bank reconciliation data or Payroll Mate 2008 bank reconciliation data`,
		`.resx`:        `Payroll Mate file`,
		`.rpf`:         `Raven Check converter payment`,
		`.s07`:         `TaxCalc 2007 data`,
		`.s12`:         `WISO Steuer-Sparbuch 2012 data`,
		`.saf`:         `SelfAccounts data files`,
		`.saj`:         `Sage 50 folder`,
		`.say`:         `Saya Matrix accounting database`,
		`.sba`:         `SpeedBalance accounting data`,
		`.sbc`:         `Microsoft Office Accounting company shortcut`,
		`.sbd`:         `Microsoft Office Accounting company data`,
		`.sbf`:         `SmartBroker data file`,
		`.scd`:         `TurboTax schedule descriptions data`,
		`.sdy`:         `StarMoney financial data`,
		`.seam`:        `Sales report`,
		`.sic`:         `Quicken 2002 order data`,
		`.sie`:         `Swedish Accounting data format`,
		`.skg`:         `Skrooge data`,
		`.slp`:         `Timeslips data`,
		`.ssg`:         `Investor's Toolkit stock selection guide`,
		`.stc`:         `eSignal stretch chart`,
		`.stm`:         `Medlin Payroll Software statement layout or LloydsTSB bank statement data`,
		`.stx`:         `StockChartX data`,
		`.t00`:         `TaxCut federal data file`,
		`.t01`:         `TaxCut 2001 tax return data or TAXWIZ Deluxe tax data`,
		`.t02`:         `TaxCut 2002 tax return data`,
		`.t03`:         `TaxCut 2003 tax return file`,
		`.t04`:         `TaxCut 2004 tax return file`,
		`.t05`:         `TaxCut 2005 tax return data`,
		`.t06`:         `TaxCut 2006 tax return`,
		`.t07`:         `TaxCut 2007 tax return file`,
		`.t08`:         `TaxCut 2008 tax return data`,
		`.t09`:         `At Home 2009 tax return data`,
		`.t10`:         `At Home 2010 tax return form`,
		`.t11`:         `At Home 2011 tax return data`,
		`.t12`:         `H&R Block At Home 2012 tax return data`,
		`.t13`:         `H&R Block 2013 tax return`,
		`.t14`:         `H&R Block 2014 tax return`,
		`.t15`:         `H&R Block 2015 tax return`,
		`.t16`:         `H&R Block 2016 tax return`,
		`.t17`:         `H&R Block 2017 tax return`,
		`.t18`:         `H&R Block 2018 tax return`,
		`.t99`:         `Kiplinger tax cut`,
		`.ta1`:         `TaxACT 2001 tax form`,
		`.ta2`:         `TaxACT document`,
		`.ta4`:         `TaxACT tax return form`,
		`.ta5`:         `TaxACT tax return form`,
		`.ta6`:         `TaxACT tax year 2006 form`,
		`.ta8`:         `TaxACT tax year 1998 form`,
		`.ta9`:         `TaxACT tax document`,
		`.tax`:         `TurboTax tax return`,
		`.tax08`:       `TurboTax 2008 tax return file`,
		`.tax09`:       `TurboTax 2009 tax return file`,
		`.tax10`:       `TurboTax 2010 tax return`,
		`.tax11`:       `TurboTax 2011 tax return`,
		`.tax12`:       `TurboTax 2012 tax return`,
		`.tax13`:       `TurboTax tax return`,
		`.tax14`:       `TurboTax 2014 tax return`,
		`.tax15`:       `TurboTax tax return 2015`,
		`.tax16`:       `TurboTax tax return 2016`,
		`.tax17`:       `TurboTax tax return 2017`,
		`.tax2008`:     `TurboTax 2008 tax return`,
		`.tax2009`:     `TurboTax 2009 tax return data`,
		`.tax2010`:     `TurboTax 2010 tax return`,
		`.tax2011`:     `TurboTax 2011 tax return`,
		`.tax2012`:     `TurboTax 2012 tax return data`,
		`.tax2013`:     `TurboTax tax return 2013`,
		`.tax2014`:     `TurboTax tax return 2014`,
		`.tax2015`:     `TurboTax tax return 2015`,
		`.tax2016`:     `TurboTax tax return 2016`,
		`.tax2017`:     `TurboTax tax return 2017`,
		`.tax2018`:     `TurboTax tax return 2018 file`,
		`.tb2`:         `TASBooks accounting backup file`,
		`.tbp`:         `TASBooks accounting data file`,
		`.tdr`:         `Medlin Payroll Software tax deposit record file`,
		`.tfx`:         `Tax exchange file format`,
		`.tkr`:         `eSignal ticker data`,
		`.tlg`:         `QuickBooks transaction log`,
		`.tom`:         `Total Office Manager accounting data`,
		`.tpl`:         `Timeslips TSImport template`,
		`.trm`:         `eSignal Trade Manager file`,
		`.trn`:         `Medlin Payroll Software current year transactions file`,
		`.tt10`:        `Intuit Turbotax 2010 tax return`,
		`.tt11`:        `TurboTax Canada 2011 tax return`,
		`.tt12`:        `TurboTax 2012 tax return`,
		`.tt13`:        `TurboTax 2013 tax return file`,
		`.tt14`:        `TurboTax 2014 tax return data`,
		`.tt15`:        `TurboTax 2015 tax return`,
		`.tt16`:        `TurboTax 2016 tax return`,
		`.tt17`:        `TurboTax 2017 tax return`,
		`.tt18`:        `TurboTax 2018 tax return`,
		`.tt2012state`: `TurboTax 2012 state tax form`,
		`.tt2013state`: `TurboTax 2013 state tax form`,
		`.tt2014state`: `TurboTax 2014 state tax form`,
		`.tt2015state`: `TurboTax 2015 state tax form`,
		`.tt2016state`: `TurboTax 2016 state tax form`,
		`.tt2017state`: `TurboTax 2017 state tax form`,
		`.txf`:         `Tax Exchange Format`,
		`.u08`:         `UFile data`,
		`.u10`:         `UFile 2010 tax return file`,
		`.u11`:         `UFile 2011 tax return file`,
		`.u12`:         `UFile 2012 tax return`,
		`.v11`:         `ESR v11 data`,
		`.vbpf1`:       `Virtual Business - Personal Finance data`,
		`.vdf`:         `VersaCheck database`,
		`.vmb`:         `Quicken 2002 order data`,
		`.vnd`:         `Medlin Accounting vendor information`,
		`.vyp`:         `GE Money Bank financial data exchange format`,
		`.vyr`:         `JAPO data`,
		`.wac`:         `WISCO Accounts storage`,
		`.xaa`:         `XML audit data`,
		`.xeq`:         `Sage MAS 90 data`,
		`.xic`:         `DIF Freedom data`,
		`.zdb`:         `Quicken data`,
		`.zix`:         `Quicken encrypted data`,
		`.zka`:         `Quicken Win version 6 file`,
	}
	//DangerousExtensions are file extensions that are known to contain sensitive data, not to be stored in source code repositories or other shared spaces
	//see https://www.file-extensions.org/filetype/extension/name/encoded-and-encrypted-files/sortBy/extension/order/asc/page/1
	DangerousExtensions = map[string]string{
		`.$cr`:               `Roxio Retrieve encrypted data`,
		`.$efs`:              `Encrypted EFS data`,
		`.1pif`:              `1Password Interchange Format`,
		`.a2r`:               `KittyXplorer encrypted archive`,
		`.aas`:               `Archos signed encrypted data`,
		`.abc`:               `Adobe ActionScript byte code`,
		`.abcd`:              `AudioVisual book data`,
		`.acl`:               `ArchiCrypt Live secured data`,
		`.acsm`:              `Adobe Content Server Message data`,
		`.ad`:                `AppleDouble encoded data`,
		`.adoc`:              `Authentica Secure Office encoded Word document`,
		`.aee`:               `ASUS Data Security Manager protected data`,
		`.aen`:               `Inventus Antum secured encrypted data`,
		`.aepkey`:            `Advanced Encryption Package key data`,
		`.aes`:               `AES Crypt encrypted data`,
		`.aes256`:            `Insurance.aes256 encrypted file`,
		`.aex`:               `PGP armored extracted public encryption key`,
		`.aexpk`:             `PGP armored extracted public key`,
		`.afp`:               `FileProtector encrypted data`,
		`.afs3`:              `AFS 3 Basic encrypted data`,
		`.agilekeychain`:     `1Password data`,
		`.alk`:               `DataLocker encrpyted data`,
		`.aos`:               `Archos signed encrypted data`,
		`.appt`:              `Authentica Secure Office protected PowerPoint presentation`,
		`.apv`:               `Acerose password data`,
		`.apw`:               `Any Password password cache`,
		`.arm`:               `SoftwarePassport protection system`,
		`.asc`:               `PGP (Pretty Good Privacy) signature`,
		`.asec`:              `Google Android encrypted application package`,
		`.asice`:             `Associated Signature Container (ASiC-E)`,
		`.atc`:               `AttacheCase encrypted file`,
		`.att`:               `ZipLip secure e-mail message`,
		`.aut`:               `Xitami webserver admin password`,
		`.auth`:              `ShopSite store authorization`,
		`.avn`:               `altaVENTE application user notes`,
		`.awsec`:             `Vodafone Secure Content Locker encrypted data or VMware Airwatch encrypted data file`,
		`.azf`:               `AirZip FileSECURE secure format`,
		`.azs`:               `AirZip FileSECURE secure format`,
		`.b2a`:               `Binary to ASCII (BTOA) encoded data`,
		`.base64`:            `Base64 file format`,
		`.bexpk`:             `PGP binary extracted public key file`,
		`.bfa`:               `BlowFish encrypted data`,
		`.bfe`:               `bcrypt - BlowFish file encryption`,
		`.bioexcess`:         `MyWinLocker protected data`,
		`.bmpenx`:            `Encrypted BMP picture image`,
		`.bms`:               `BIOWRAP multi-layer security data`,
		`.bnc`:               `Bojanov Encryptor encrypted data`,
		`.box`:               `Microsoft Store download data`,
		`.bpk`:               `Nero SecurDisc public key`,
		`.bpw`:               `Bitser password file`,
		`.bsk`:               `Nero SecurDisc private key`,
		`.btoa`:              `Binary-to-ASCII file format`,
		`.c2v`:               `WellSight Systems license information file`,
		`.cae`:               `Caditor encrypted document`,
		`.can`:               `Can Encryptor/Decryptor encrypted data`,
		`.ccitt`:             `CCITT Group 3 and Group 4 encoded fax`,
		`.ccp`:               `Two Brothers Software encrypted data`,
		`.cdb`:               `FreeOTFE key`,
		`.cef`:               `SanDisk CruzerLock encrypted data`,
		`.cfd`:               `CryptoForge encrypted document`,
		`.cfe`:               `CryptoForge encrypted data file`,
		`.cfog`:              `Cloudfogger encrypted data`,
		`.cgp`:               `PixelCryptor encrypted data`,
		`.chi`:               `TOMBO encrypted data`,
		`.chml`:              `chameleon encrypted data`,
		`.cip`:               `CryptoBuddy encrypted file or Ghost Keylogger file`,
		`.clk`:               `WatchGuard cloaked data`,
		`.clu`:               `IBM PCI cryptographic coprocessor code file`,
		`.clx`:               `Ceelox SecureMail encrypted document`,
		`.cml`:               `CryptoMailer encrypted data`,
		`.cng`:               `CryptoNG encrypted data`,
		`.cpt`:               `CCRYPT encrypted data or dBASE encrypted memo`,
		`.cpx`:               `CryptaPix encrypted image`,
		`.crl`:               `Certificate revocation list`,
		`.crpt`:              `Cryptosaurus encrypted data`,
		`.cry`:               `Cryptainer encrypted volume`,
		`.crypt`:             `WhatsApp encrypted backup (original)`,
		`.crypt10`:           `WhatsApp Messenger encrypted message database backup`,
		`.crypt11`:           `WhatsApp Messenger encrypted message database backup`,
		`.crypt12`:           `WhatsApp Messenger message database`,
		`.crypt5`:            `WhatsApp Messenger encrypted message database backup`,
		`.crypt6`:            `WhatsApp Messenger encrypted message database backup`,
		`.crypt7`:            `WhatsApp Messenger encrypted message database backup`,
		`.crypt8`:            `WhatsApp Messenger message database`,
		`.crypt9`:            `WhatsApp Messenger encrypted message database backup`,
		`.crypted`:           `Ashampoo WinOptimizer encrypted data`,
		`.cryptomite`:        `CryptoMite encrypted archive`,
		`.cryptra`:           `Cryptra encrypted data`,
		`.csj`:               `RIM CSJ registration data`,
		`.ctz`:               `Cherrytree password protected data`,
		`.cxt`:               `Adobe Director protected cast data`,
		`.cyp`:               `Cypherus encrypted archive`,
		`.czip`:              `ZG encrypted zip archive`,
		`.daf`:               `Digital Anchor Manager data`,
		`.daz`:               `DIABASS encrypted patient data`,
		`.db`:                `Enpass encrypted database`,
		`.db.crypt5`:         `WhatsApp Messenger encrypted message database backup`,
		`.db.crypt7`:         `WhatsApp Messenger encrypted message database backup`,
		`.db.crypt8`:         `WhatsApp Messenger message database backup`,
		`.dc4`:               `ViaThinkSoft (De)Coder encrypted data`,
		`.dcf`:               `Safetica encrypted archive`,
		`.dco`:               `DisCryptor encrypted archive`,
		`.dcv`:               `DriveCrypt encrypted volume`,
		`.des`:               `Interscope BlackBox data`,
		`.devicesalt`:        `Nook encrypted data`,
		`.dhcd`:              `DHCD Computing file`,
		`.dim`:               `Direct Internet Message Encapsulation DIME data`,
		`.dlm`:               `Dmailer encrypted data`,
		`.doce`:              `Document Manager encrypted Microsoft Word document`,
		`.docenx`:            `Egis encrypted Word document`,
		`.docl`:              `Document Manager locked Word document`,
		`.docxenx`:           `Egis encrypted Word DOCX file`,
		`.docxl`:             `Document Manager locked Word Open XML document`,
		`.dotmenx`:           `Egis encrypted Word DOTM document`,
		`.dotxenx`:           `Egis encrypted Word DOTX file`,
		`.dpd`:               `Dekart Private Disk encrypted disk image`,
		`.drc`:               `DriveCrypt container file`,
		`.dsa`:               `PKCS #7 signature`,
		`.dsc`:               `Nikon Coolpix disk identification data`,
		`.dse`:               `DAZ Studio encrypted script`,
		`.dsf`:               `PC-TRUST signed document`,
		`.dst`:               `ViPNet products encryption key set`,
		`.dwk`:               `Autodesk AutoCAD locked DWG drawing`,
		`.dwx`:               `CADLock locked AutoCAD drawing`,
		`.ecr`:               `Ecrypt encrypted data`,
		`.edat`:              `Sony Playstation Portable PSP encrypted data`,
		`.edc`:               `Kryptel (Lite) Decoder/Encoder data`,
		`.ee`:                `Encrypt Easy encrypted data`,
		`.eea`:               `Encrypted e-mail attachment`,
		`.eee`:               `3eee Triple Encryption encrypted data`,
		`.efa`:               `Ecrypt 2005 encrypted data`,
		`.efc`:               `FAIRCOPY encrypted fair copy`,
		`.eff`:               `eFileFolders file format`,
		`.efl`:               `Encryptafile encrypted data`,
		`.efr`:               `Encryptafile private key`,
		`.efs`:               `Microsoft Windows Encrypting File System`,
		`.efu`:               `Encryptafile public key`,
		`.egisenc`:           `Egis encrypted data`,
		`.egisenx`:           `Egis encryped data`,
		`.egs`:               `GIS Software encrypted grid shape data`,
		`.eid`:               `Faena MyID encrypted data`,
		`.ekb`:               `SIEMENS Automation License Manager data`,
		`.embp`:              `Mobipocket eBook encrypted auxiliary data`,
		`.emc`:               `Striata Reader encrypted document`,
		`.enc`:               `Uuencode encoded data or BlackIce PC Protection evidence log or CopySafe PDF encrypted document or Media Safe encrypted data`,
		`.enk`:               `Sybase Enterprise Portal security key`,
		`.eno`:               `FruitfulTime TaskManager encrypted note`,
		`.ent`:               `Entrust Entelligence Security Provider secured data`,
		`.eoc`:               `EncryptOnClick encrypted data`,
		`.epf`:               `Entrust Entelligence profile`,
		`.epk`:               `LG firmware archive`,
		`.esf`:               `Steganos Password Manager container`,
		`.eslock`:            `ES File Explorer encrypted data`,
		`.esm`:               `Europay security module`,
		`.etxt`:              `Encrypted text`,
		`.exc`:               `eDataSecurity Management archive`,
		`.exportedfavorites`: `Transmit for Mac exported logins file`,
		`.ezk`:               `EasyKrypt encrypted data`,
		`.fcfe`:              `Microsoft Access encrypted database`,
		`.fdp`:               `Protector Suite QL encrypted file`,
		`.fgp`:               `Folder Guard passwords data`,
		`.filelock`:          `FileLock data`,
		`.fl`:                `DRM Packager forward lock`,
		`.flk`:               `Folder Lock encrypted data`,
		`.flka`:              `Folder Lock encrypted portable folder`,
		`.flkb`:              `Folder Lock encrypted folder`,
		`.flkw`:              `Folder Lock encrypted file`,
		`.flwa`:              `Folder Lock wallet`,
		`.fpa`:               `Front Panel Designer encrypted order data`,
		`.fpenc`:             `Mobile File Encryption MIDlet encrypted data`,
		`.fss`:               `Splitty split data`,
		`.ftil`:              `e-Hastakshar contract note`,
		`.fve`:               `Windows BitLocker full volume encrypted data`,
		`.gfl`:               `Gilisoft File Lock Pro encrypted archive`,
		`.gifenx`:            `Egis encrypted GIF picture image`,
		`.gpg`:               `GNU Privacy Guard public keyring`,
		`.grd`:               `StrongDisk encrypted disk image`,
		`.gte`:               `GigaTrust protected data`,
		`.gxk`:               `Galaxkey File Manager encrypted data`,
		`.hbx`:               `BinHex encoded data`,
		`.hc`:                `VeraCrypt disk volume`,
		`.hde`:               `NAUPA File Encryptor encrypted data`,
		`.hds`:               `Windows Digital Right Management data`,
		`.hdt`:               `Proactive Windows Security Explorer hash data`,
		`.hex`:               `Macintosh BinHex encoded file archive (ASCII)`,
		`.hid`:               `KeepSafe encrypted data`,
		`.hid2`:              `KeepSafe encrypted photo`,
		`.hop`:               `Hippon protected data`,
		`.hpg`:               `Hide Photos encrypted photo container`,
		`.hsf`:               `Lizard Protector Web Content Security protected web content`,
		`.hsh`:               `Microsoft IIS NNTP hash data`,
		`.htmlenx`:           `Egis encrypted HTML file`,
		`.ibe`:               `IBECrypto encrypted file`,
		`.ica`:               `Identity Compass encrypted answers`,
		`.icd`:               `SafeDisc encrypted digital rights management data`,
		`.icp`:               `Identity Compass encrypted profile`,
		`.ifs`:               `InfoSlips secure information package`,
		`.img3`:              `Apple iOS Img3 encrypted or signed container`,
		`.isk`:               `Druvaa inSync client key file`,
		`.ism`:               `SimulationX encrypted model`,
		`.ivex`:              `Worldviz Vizard encrypted data`,
		`.iwa`:               `Apple iWork document archive`,
		`.ize`:               `IZArc encrypted archive`,
		`.jbc`:               `Jetico BestCrypt container`,
		`.jcrypt`:            `JCRYPT encrypted file`,
		`.jmc`:               `JM-Crypt encrypted data`,
		`.jmce`:              `JM-Crypt encrypted file`,
		`.jmck`:              `JM-Crypt encrypted file`,
		`.jmcp`:              `JM-Crypt encrypted file`,
		`.jmcr`:              `JM-Crypt encrypted file`,
		`.jmcx`:              `JM-Crypt encrypted data`,
		`.jpegenx`:           `Egis encrypted JPEG picture image`,
		`.jpegx`:             `Egis encrypted JPEG picture image`,
		`.jpgenx`:            `Egis encrypted JPG picture image`,
		`.jpgx`:              `Egis encrypted JPG bitmap image`,
		`.jpg_encrypted`:     `Google Android encrypted JPEG picture image`,
		`.jpi`:               `Jupiter encrypted XML file`,
		`.jrl`:               `Top Secret Crypto Gold top secret journal file`,
		`.jse`:               `JScript encoded script`,
		`.jsn`:               `Shield Now shield data`,
		`.jwk`:               `JSON web key`,
		`.k2p`:               `Kryptel encrypted data`,
		`.kdb`:               `KeePass encrypted passwords database`,
		`.kdbx`:              `KeePass password database`,
		`.kde`:               `Kaspersky KryptoStorage encrypted data`,
		`.key`:               `Licence or encrypted security key or Avira AntiVir Personal license key`,
		`.keychain`:          `Apple Keychain password data`,
		`.kgb`:               `Kremlin Encrypt data`,
		`.kge`:               `KGB Archiver encrypted compressed archive`,
		`.kne`:               `KeyNote encrypted data`,
		`.ks`:                `Keystore data`,
		`.ksd`:               `KeepSafe encrypted data`,
		`.kwm`:               `WM Keeper CLASSIC key data`,
		`.leotmi`:            `Privacy Lock protected picture`,
		`.lf`:                `SoftwareKey license`,
		`.lgb`:               `QuickBooks little green box`,
		`.lma`:               `P's Logik-Manager protect file`,
		`.lock3`:             `BlackBerry encrypted 3GP data`,
		`.lok`:               `FileWrangler encrypted archive file`,
		`.lp7`:               `LP7Signer digital signed data`,
		`.lrs`:               `Lexar encrypted data`,
		`.lxv`:               `Lexar Secure II encrypted archive file`,
		`.macs`:              `MADRIX encrypted script file`,
		`.mbs`:               `Multi-Purpose Internet Mail Extensions`,
		`.mbz5`:              `Micros encrypted password database`,
		`.mcat`:              `Meerecat File Guard encrypted data`,
		`.mck`:               `Macro Keys encrypted macro`,
		`.mcrp`:              `MobyExplorer encrypted data`,
		`.menc`:              `Microsoft Windows Mobile encrypted data`,
		`.meo`:               `MEO encrypted data`,
		`.mfs`:               `MetFS encrypted FUSE based filesystem`,
		`.mhtenx`:            `Egis encrypted HTM file`,
		`.mhtmlenx`:          `Egis encrypted MHTML document`,
		`.migitallock`:       `Migital encrypted data`,
		`.mim`:               `Multi-Purpose Internet Mail Extensions`,
		`.mjd`:               `Adobe Acrobat MIME encoded job definition`,
		`.mkey`:              `CompeGPS Land registration key`,
		`.mkeyb`:             `CompeGPS Land registration key`,
		`.mnc`:               `AutoCAD compiled menu`,
		`.mono`:              `Monolith munged encoded data`,
		`.mpqe`:              `Blizzard encrypted game data`,
		`.msd`:               `Secured and encrypted data`,
		`.mse`:               `3ds Max encrypted MAXScript script`,
		`.mtd`:               `Microsoft Live Mesh hash`,
		`.mxls`:              `MaxL encrypted script`,
		`.nc`:                `mcrypt encrypted archive`,
		`.nef`:               `Nero BackItUp encrypted data`,
		`.nip`:               `Microsoft DRM (Digital Right Management) data`,
		`.nsx`:               `Synology DiskStation Manager exported note`,
		`.ntx`:               `yEnc32 encoded data or theWord encrypted module file`,
		`.obb`:               `Android opaque binary blob archive`,
		`.ontx`:              `theWord encrypted module`,
		`.opef`:              `OmniPass encrypted folder`,
		`.osf`:               `ICZ OriSAFE data`,
		`.otp`:               `Top Secret Crypto Gold one time pad key file`,
		`.p12`:               `PFX file (Personal Information Exchange)`,
		`.p7`:                `Elemica eSignature digital signature`,
		`.p7a`:               `PKCS #7 signature`,
		`.p7e`:               `SecureSoft encrypted data`,
		`.p7m`:               `S/MIME digital signature or SecureSoft encrypted data`,
		`.p7s`:               `PKCS #7 signature`,
		`.p7x`:               `Application digital certificate`,
		`.p7z`:               `S/MIME compressed e-mail message`,
		`.pae`:               `PowerArchiver encrypted archive`,
		`.pandora`:           `Pandora private multimedia data`,
		`.passwordwallet4`:   `PasswordWallet encrypted data file`,
		`.paw`:               `pawaaFILE file format`,
		`.pcp`:               `RCF EnCoder/DeCoder encoded data`,
		`.pcxm`:              `SQL Server encrypted forms backup`,
		`.pdc`:               `Lizard Safeguard secure PDF document`,
		`.pde`:               `PowerDesk encrypted data`,
		`.pdfenx`:            `Egis encrypted PDF document`,
		`.pdfl`:              `Document Manager locked PDF document`,
		`.pdv`:               `Privacy Drive volume data`,
		`.pem`:               `Privacy Enhanced Mail security certificate`,
		`.pf`:                `Aladdin Systems private data or Stuffit private archive`,
		`.pfx`:               `Certificate`,
		`.pgp`:               `Pretty Good Privacy encrypted key`,
		`.pi2`:               `Portrait Innovations high resolution image`,
		`.pie`:               `Studio2 high resolution encrypted image`,
		`.pjpg`:              `Microsoft Rights Management protected JPG image`,
		`.pkcs12`:            `Personal information exchange data`,
		`.pkd`:               `Eurotherm Hydra History encrypted data`,
		`.pkey`:              `PowerKey encrypted data`,
		`.pkf`:               `SecretAgent key`,
		`.pkk`:               `PuTTYgen private key`,
		`.pkpass`:            `Apple Wallet pass data`,
		`.pkr`:               `Pretty Good Privacy public keyring`,
		`.ple`:               `Messenger Plus! Live encrypted log`,
		`.pnne`:              `Norton Encrypt for Mac`,
		`.poo`:               `On-Line game protected file`,
		`.potmenx`:           `Egis encrypted PowerPoint POTM file`,
		`.pp7m`:              `Entrust Entelligence Security Provider password-encrypted data`,
		`.ppenc`:             `Ashampoo Magical Security encrypted data`,
		`.ppk`:               `PuTTY Win32 Telnet/SSH client private key`,
		`.ppsenx`:            `Microsoft PowerPoint encrypted PPS slideshow`,
		`.ppsxenx`:           `Egis encrypted PowerPoint PPSX file`,
		`.ppte`:              `Document Manager encrypted PowerPoint presentation`,
		`.pptenx`:            `Egis encrypted Powerpoint PPT data`,
		`.pptl`:              `Document Manager locked PowerPoint presentation`,
		`.pptxenx`:           `Egis encrypted Powerpoint PPTX presentation`,
		`.prv`:               `SecretAgent private key`,
		`.prvkr`:             `Pretty Good Privacy private keyring data`,
		`.psw`:               `Password Depot data`,
		`.pswx`:              `Password Depot password data`,
		`.ptxt`:              `Microsoft Rights Management protected TXT file`,
		`.puf`:               `Puffer encrypted data`,
		`.pvk`:               `Private key`,
		`.pvr`:               `SecretAgent private key`,
		`.pwa`:               `Password Agent encrypted data`,
		`.pwl`:               `Microsoft Windows password data`,
		`.pwv`:               `Secret Space Encryptor password vault archive`,
		`.qze`:               `QZip encrypted data`,
		`.rae`:               `TrueZIP encrypted ZIP archive file`,
		`.raes`:              `TrueZIP encrypted ZIP archive`,
		`.rarenx`:            `Egis encrypted RAR archive`,
		`.raw`:               `Sentry 2020 encryption data`,
		`.rbb`:               `Top Secret Crypto Gold random bits bin data`,
		`.rdi`:               `Rohos encrypted disk image`,
		`.rdk`:               `Blackberry RDK data`,
		`.rdz`:               `RemoteDocs document`,
		`.rem`:               `BlackBerry encrypted data`,
		`.req`:               `SSL request data`,
		`.rfp`:               `RoboForm Passcard`,
		`.rgss2a`:            `RPG Maker VX RGSS encrypted archive`,
		`.rng`:               `Top Secret Crypto Gold RSA key ring file`,
		`.rpgmvm`:            `RPG Maker MV encrypted M4A audio`,
		`.rpgmvo`:            `RPG Maker MV encrypted OGG audio`,
		`.rpgmvp`:            `RPG Maker MV encrypted PNG image`,
		`.rpz`:               `Crystal Reports ZIP compressed and encrypted report file`,
		`.rsa`:               `RSA digital certificate`,
		`.rsdf`:              `RapidShare download settings`,
		`.rte`:               `RTEncoder RTE encoded data`,
		`.rxf`:               `Resco encrypted data`,
		`.rzk`:               `File Crypt password data`,
		`.rzs`:               `Red Zion security data`,
		`.rzx`:               `File Crypt encrypted data`,
		`.s1j`:               `Sealed file`,
		`.saa`:               `SecretAgent encrypted archive file`,
		`.safe`:              `eCypher cryptographic container or SIGLock encrypted data`,
		`.SafeText`:          `Encrypted text`,
		`.sbe`:               `SafeBoot encrypted archive`,
		`.sccef`:             `StreamCryptor chunked encrypted file`,
		`.sce`:               `Associated Signature Container (ASiC-E)`,
		`.scke`:              `SpyClock encrypted video`,
		`.sda`:               `Pretty Good Privacy (PGP) encrypted executable`,
		`.sdc`:               `Microsoft Secure Download Cabinet archive`,
		`.sde`:               `Steganos Disk Encryption file format`,
		`.sdo`:               `Signere.no signed document`,
		`.sdoc`:              `Microsoft Word sealed document`,
		`.sdsk`:              `SafeHouse private storage volume data`,
		`.sdtid`:             `RSA soft-token`,
		`.sec`:               `Pretty Good Privacy secret key ring file`,
		`.secure`:            `Septium secured document`,
		`.sef`:               `Encryptafile digital signature or Steganos encrypted file`,
		`.sfi`:               `SafeFolder encrypted data`,
		`.sgn`:               `Signet encrypted data`,
		`.sgz`:               `Sigza’s SigzaLock encrypted file`,
		`.shy`:               `ShyFile encrypted data`,
		`.sign`:              `GNU Privacy Guard data`,
		`.signed`:            `macOS (OS X) data signature`,
		`.sjpg`:              `Sealed JPG data`,
		`.ska`:               `Pretty Good Privacy (PGP) secret keyring`,
		`.skr`:               `PGP Pretty Good Privacy private keyring`,
		`.slm`:               `Gallery Lock hidden media`,
		`.smbp`:              `Mobipocket eBook secured auxiliary file`,
		`.sme`:               `SmartEncryptor encrypted archive`,
		`.smht`:              `Sealed MHT archive`,
		`.spd`:               `SpyProof! encrypted disk data`,
		`.spk`:               `SpyProof! encrypted symmetric key`,
		`.spn`:               `Sealed PNG graphic`,
		`.sppt`:              `Sealed Microsoft PowerPoint presentation`,
		`.spsx`:              `IBM SPSS password protected data`,
		`.sth`:               `Lotus Domino stash data file`,
		`.sti`:               `Sealed TIFF file`,
		`.stxt`:              `Sealed text document`,
		`.suf`:               `ccrypt encrypted data`,
		`.svq`:               `InfoBind file format`,
		`.svz`:               `Savez data`,
		`.switch`:            `Egress Switch secured package`,
		`.sxl`:               `Sealed Excel worksheet file`,
		`.sxm`:               `Sealed XML document file`,
		`.sxml`:              `Sealed XML document`,
		`.tc`:                `TrueCrypt disk volume image`,
		`.tifenx`:            `egis encrypted TIFF image`,
		`.tmw`:               `Timeless Time & Expense multi-user security data`,
		`.tpm`:               `Microsoft trusted platform module password data`,
		`.tsc`:               `Top Secret Crypto Gold encrypted file`,
		`.txtenx`:            `Egis encrypted TXT file`,
		`.tzp`:               `TrueZIP ecnrypted JAR Java archive`,
		`.uea`:               `Protector Suite QL data`,
		`.ueaf`:              `Upek protected single data`,
		`.ueed`:              `Uconomix Encryption Engine encrypted directory`,
		`.uenc`:              `UltraEdit encrypted text`,
		`.uhh`:               `Eurotherm Hydra History encrypted data`,
		`.uu`:                `Uuencoded (compressed) file archive (ascii)`,
		`.uud`:               `UUDecoded file`,
		`.uue`:               `UUEncoded data`,
		`.v11pf`:             `ACDSee private folder`,
		`.v2c`:               `WellSight Systems HASP SRM license information data`,
		`.vbox`:              `SecurityBox encrypted data`,
		`.vdata`:             `Vaulty hidden picture or video`,
		`.vf3`:               `Vaultlet Suite encrypted data`,
		`.viivo`:             `Viivo encrypted data`,
		`.vmdf`:              `MyWinLocker encrypted virtual drive`,
		`.vme`:               `Virtual Matrix encryption data`,
		`.vp`:                `Verilog encrypted source code`,
		`.vsf`:               `Voltage SecureFile encrypted document`,
		`.vzn`:               `Windows VZN picture image`,
		`.walletx`:           `Enpass backup`,
		`.wbc`:               `Webshots collection image format`,
		`.wls`:               `Renault R-Link encrypted authorization data`,
		`.wmg`:               `SecureDoc encrypted hard drive control data`,
		`.wmt`:               `WinMount data`,
		`.wza`:               `Encryption Wizard archive file`,
		`.wzd`:               `Encryption Wizard encrypted individual data`,
		`.x26`:               `Taser X26 encrypted record`,
		`.xcon`:              `Conceal encrypted data file`,
		`.xdb`:               `HyperCD HyperLOCK data`,
		`.xdc`:               `Total Commander with DarkCrypt IV plug-in encrypted data`,
		`.xef`:               `WinAce encrypted data`,
		`.xfi`:               `xICE Desktop encrypted data`,
		`.xfl`:               `xICE Desktop encrypted folder`,
		`.xia`:               `Chiasmus encrypted data`,
		`.xlamenx`:           `Egis encrypted Excel XLAM file`,
		`.xlse`:              `Document Manager encrypted Excel spreadsheet`,
		`.xlsenx`:            `Egis encrypted Excel XLS spreadsheet`,
		`.xlsl`:              `Document Manager locked Excel spreadsheet`,
		`.xlsxenx`:           `Egis encrypted Excel XLSX spreadsheet`,
		`.xlsxl`:             `Document Manager locked Excel Open XML workbook`,
		`.xmm`:               `GEX MP3 satellite receiver saved data`,
		`.xrm-ms`:            `Microsoft security certificate`,
		`.xtea`:              `XTEA encyrpted data`,
		`.xxe`:               `XXEncoded data`,
		`.y8pd`:              `Password Finder exported password`,
		`.yenc`:              `yEnc encoded archive`,
		`.ync`:               `yEnc encoded data`,
		`.zbb`:               `ZEMAX black box data`,
		`.zbd`:               `Zebedee encrypted data`,
		`.zipenx`:            `Egis encrypted ZIP file`,
		`.zix`:               `ZixCorp encrypted data`,
		`.zps`:               `Zebra Portable Safe file`,
		`.zxn`:               `PhotoEncrypt encrypted photo`,
		`.__b`:               `File Splitter & Joiner encrypted archive`,
		`.___fpe`:            `Folder Password Expert protected folder`,
	}
)
